# Generated by Django 5.2.5 on 2026-10-01 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('winner_team', models.CharField(max_length=100)),
                ('winner_code', models.CharField(max_length=10)),
                ('runner_up', models.CharField(max_length=100)),
                ('final_venue', models.CharField(max_length=150)),
                ('final_margin', models.CharField(max_length=100)),
                ('player_of_season', models.CharField(max_length=100)),
                ('orange_cap_player', models.CharField(max_length=100)),
                ('orange_cap_runs', models.IntegerField(default=0)),
                ('orange_cap_team', models.CharField(default='', max_length=50)),
                ('purple_cap_player', models.CharField(max_length=100)),
                ('purple_cap_wickets', models.IntegerField(default=0)),
                ('purple_cap_team', models.CharField(default='', max_length=50)),
                ('total_sixes', models.IntegerField(default=0)),
                ('total_fours', models.IntegerField(default=0)),
                ('total_runs', models.IntegerField(default=0)),
                ('total_matches', models.IntegerField(default=0)),
                ('congratulation_message', models.TextField()),
                ('theme_color', models.CharField(default='#F59E0B', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeasonStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('role', models.CharField(default='Batsman', max_length=50)),
                ('matches', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=0)),
                ('balls_faced', models.IntegerField(default=0)),
                ('strike_rate', models.FloatField(default=0.0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('economy', models.FloatField(default=0.0)),
                ('highest_score', models.CharField(default='0', max_length=20)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='api.season')),
            ],
            options={
                'ordering': ['-runs', '-sixes'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('match_stage', models.CharField(default='League', max_length=50)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('winner', models.CharField(max_length=100)),
                ('win_margin', models.CharField(default='', max_length=100)),
                ('toss_winner', models.CharField(max_length=100)),
                ('toss_decision', models.CharField(max_length=20)),
                ('venue', models.CharField(max_length=150)),
                ('player_of_match', models.CharField(max_length=100)),
                ('team1_runs', models.IntegerField(default=0)),
                ('team1_wickets', models.IntegerField(default=0)),
                ('team2_runs', models.IntegerField(default=0)),
                ('team2_wickets', models.IntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.season')),
            ],
        ),
    ]
