from django.core.management.base import BaseCommand
from api.models import Season, PlayerSeasonStat, Match

class Command(BaseCommand):
    help = 'Seeds IPL 2008 to 2026 data according to exact specified winner & cap lists'

    def handle(self, *args, **options):
        self.stdout.write("Updating IPL Database with exact Orange & Purple Cap Winners (2008-2026)...")
        Match.objects.all().delete()
        PlayerSeasonStat.objects.all().delete()
        Season.objects.all().delete()

        seasons_data = [
            {
                'year': 2008,
                'winner_team': 'Rajasthan Royals',
                'winner_code': 'RR',
                'runner_up': 'Chennai Super Kings',
                'final_venue': 'DY Patil Stadium, Navi Mumbai',
                'final_margin': 'Won by 3 wickets',
                'player_of_season': 'Shane Warne',
                'orange_cap_player': 'Shaun Marsh',
                'orange_cap_runs': 616,
                'orange_cap_team': 'Kings XI Punjab',
                'purple_cap_player': 'Sohail Tanvir',
                'purple_cap_wickets': 22,
                'purple_cap_team': 'Rajasthan Royals',
                'total_sixes': 620,
                'total_fours': 1730,
                'total_runs': 17937,
                'total_matches': 59,
                'theme_color': '#2563EB',
                'congratulation_message': '🎉 Congratulations Rajasthan Royals! The inaugural 2008 IPL Champions led by Legendary Captain Shane Warne (Won by 3 wickets)! 🏆'
            },
            {
                'year': 2009,
                'winner_team': 'Deccan Chargers',
                'winner_code': 'DC',
                'runner_up': 'Royal Challengers Bangalore',
                'final_venue': 'Wanderers Stadium, Johannesburg',
                'final_margin': 'Won by 6 runs',
                'player_of_season': 'Adam Gilchrist',
                'orange_cap_player': 'Matthew Hayden',
                'orange_cap_runs': 572,
                'orange_cap_team': 'Chennai Super Kings',
                'purple_cap_player': 'RP Singh',
                'purple_cap_wickets': 23,
                'purple_cap_team': 'Deccan Chargers',
                'total_sixes': 506,
                'total_fours': 1580,
                'total_runs': 16150,
                'total_matches': 57,
                'theme_color': '#1E3A8A',
                'congratulation_message': '🎉 Congratulations Deccan Chargers! 2009 IPL Champions with heroic leadership by Captain Adam Gilchrist (Won by 6 runs)! 🏆'
            },
            {
                'year': 2010,
                'winner_team': 'Chennai Super Kings',
                'winner_code': 'CSK',
                'runner_up': 'Mumbai Indians',
                'final_venue': 'DY Patil Stadium, Navi Mumbai',
                'final_margin': 'Won by 22 runs',
                'player_of_season': 'MS Dhoni',
                'orange_cap_player': 'Sachin Tendulkar',
                'orange_cap_runs': 618,
                'orange_cap_team': 'Mumbai Indians',
                'purple_cap_player': 'Pragyan Ojha',
                'purple_cap_wickets': 21,
                'purple_cap_team': 'Deccan Chargers',
                'total_sixes': 585,
                'total_fours': 1690,
                'total_runs': 17400,
                'total_matches': 60,
                'theme_color': '#F59E0B',
                'congratulation_message': '🎉 Congratulations Chennai Super Kings! Maiden IPL Championship title under Captain Cool MS Dhoni in 2010 (Won by 22 runs)! 🏆'
            },
            {
                'year': 2011,
                'winner_team': 'Chennai Super Kings',
                'winner_code': 'CSK',
                'runner_up': 'Royal Challengers Bangalore',
                'final_venue': 'MA Chidambaram Stadium, Chennai',
                'final_margin': 'Won by 58 runs',
                'player_of_season': 'MS Dhoni',
                'orange_cap_player': 'Chris Gayle',
                'orange_cap_runs': 608,
                'orange_cap_team': 'Royal Challengers Bangalore',
                'purple_cap_player': 'Lasith Malinga',
                'purple_cap_wickets': 28,
                'purple_cap_team': 'Mumbai Indians',
                'total_sixes': 639,
                'total_fours': 1910,
                'total_runs': 19800,
                'total_matches': 74,
                'theme_color': '#F59E0B',
                'congratulation_message': '🎉 Congratulations Chennai Super Kings! Back-to-back 2011 IPL Champions under Captain MS Dhoni (Won by 58 runs)! 🏆'
            },
            {
                'year': 2012,
                'winner_team': 'Kolkata Knight Riders',
                'winner_code': 'KKR',
                'runner_up': 'Chennai Super Kings',
                'final_venue': 'MA Chidambaram Stadium, Chennai',
                'final_margin': 'Won by 5 wickets',
                'player_of_season': 'Gautam Gambhir',
                'orange_cap_player': 'Chris Gayle',
                'orange_cap_runs': 733,
                'orange_cap_team': 'Royal Challengers Bangalore',
                'purple_cap_player': 'Morne Morkel',
                'purple_cap_wickets': 25,
                'purple_cap_team': 'Delhi Daredevils',
                'total_sixes': 731,
                'total_fours': 1950,
                'total_runs': 20300,
                'total_matches': 76,
                'theme_color': '#6F2DA8',
                'congratulation_message': '🎉 Congratulations Kolkata Knight Riders! Maiden IPL Trophy triumph in 2012 under Captain Gautam Gambhir (Won by 5 wickets)! 🏆'
            },
            {
                'year': 2013,
                'winner_team': 'Mumbai Indians',
                'winner_code': 'MI',
                'runner_up': 'Chennai Super Kings',
                'final_venue': 'Eden Gardens, Kolkata',
                'final_margin': 'Won by 23 runs',
                'player_of_season': 'Rohit Sharma',
                'orange_cap_player': 'Michael Hussey',
                'orange_cap_runs': 733,
                'orange_cap_team': 'Chennai Super Kings',
                'purple_cap_player': 'Dwayne Bravo',
                'purple_cap_wickets': 32,
                'purple_cap_team': 'Chennai Super Kings',
                'total_sixes': 680,
                'total_fours': 2010,
                'total_runs': 21000,
                'total_matches': 76,
                'theme_color': '#004BA0',
                'congratulation_message': '🎉 Congratulations Mumbai Indians! First ever IPL Championship victory in 2013 under Captain Rohit Sharma (Won by 23 runs)! 🏆'
            },
            {
                'year': 2014,
                'winner_team': 'Kolkata Knight Riders',
                'winner_code': 'KKR',
                'runner_up': 'Kings XI Punjab',
                'final_venue': 'M. Chinnaswamy Stadium, Bengaluru',
                'final_margin': 'Won by 3 wickets',
                'player_of_season': 'Gautam Gambhir',
                'orange_cap_player': 'Robin Uthappa',
                'orange_cap_runs': 660,
                'orange_cap_team': 'Kolkata Knight Riders',
                'purple_cap_player': 'Mohit Sharma',
                'purple_cap_wickets': 23,
                'purple_cap_team': 'Chennai Super Kings',
                'total_sixes': 714,
                'total_fours': 1860,
                'total_runs': 18900,
                'total_matches': 60,
                'theme_color': '#6F2DA8',
                'congratulation_message': '🎉 Congratulations Kolkata Knight Riders! 2014 Champions led by Captain Gautam Gambhir (Won by 3 wickets)! 🏆'
            },
            {
                'year': 2015,
                'winner_team': 'Mumbai Indians',
                'winner_code': 'MI',
                'runner_up': 'Chennai Super Kings',
                'final_venue': 'Eden Gardens, Kolkata',
                'final_margin': 'Won by 41 runs',
                'player_of_season': 'Rohit Sharma',
                'orange_cap_player': 'David Warner',
                'orange_cap_runs': 562,
                'orange_cap_team': 'Sunrisers Hyderabad',
                'purple_cap_player': 'Dwayne Bravo',
                'purple_cap_wickets': 26,
                'purple_cap_team': 'Chennai Super Kings',
                'total_sixes': 692,
                'total_fours': 1810,
                'total_runs': 18500,
                'total_matches': 60,
                'theme_color': '#004BA0',
                'congratulation_message': '🎉 Congratulations Mumbai Indians! 2nd IPL Trophy triumph in 2015 under Captain Rohit Sharma (Won by 41 runs)! 🏆'
            },
            {
                'year': 2016,
                'winner_team': 'Sunrisers Hyderabad',
                'winner_code': 'SRH',
                'runner_up': 'Royal Challengers Bangalore',
                'final_venue': 'M. Chinnaswamy Stadium, Bengaluru',
                'final_margin': 'Won by 8 runs',
                'player_of_season': 'David Warner',
                'orange_cap_player': 'Virat Kohli',
                'orange_cap_runs': 973,
                'orange_cap_team': 'Royal Challengers Bangalore',
                'purple_cap_player': 'Bhuvneshwar Kumar',
                'purple_cap_wickets': 23,
                'purple_cap_team': 'Sunrisers Hyderabad',
                'total_sixes': 872,
                'total_fours': 1990,
                'total_runs': 20100,
                'total_matches': 60,
                'theme_color': '#FF8225',
                'congratulation_message': '🎉 Congratulations Sunrisers Hyderabad! 2016 Champions under Captain David Warner (Won by 8 runs)! 🏆'
            },
            {
                'year': 2017,
                'winner_team': 'Mumbai Indians',
                'winner_code': 'MI',
                'runner_up': 'Rising Pune Supergiants',
                'final_venue': 'Rajiv Gandhi International Stadium, Hyderabad',
                'final_margin': 'Won by 1 run',
                'player_of_season': 'Rohit Sharma',
                'orange_cap_player': 'David Warner',
                'orange_cap_runs': 641,
                'orange_cap_team': 'Sunrisers Hyderabad',
                'purple_cap_player': 'Bhuvneshwar Kumar',
                'purple_cap_wickets': 26,
                'purple_cap_team': 'Sunrisers Hyderabad',
                'total_sixes': 705,
                'total_fours': 1840,
                'total_runs': 18800,
                'total_matches': 60,
                'theme_color': '#004BA0',
                'congratulation_message': '🎉 Congratulations Mumbai Indians! 3-time IPL Champions under Captain Rohit Sharma in 2017 (Won by 1 run)! 🏆'
            },
            {
                'year': 2018,
                'winner_team': 'Chennai Super Kings',
                'winner_code': 'CSK',
                'runner_up': 'Sunrisers Hyderabad',
                'final_venue': 'Wankhede Stadium, Mumbai',
                'final_margin': 'Won by 8 wickets',
                'player_of_season': 'MS Dhoni',
                'orange_cap_player': 'Kane Williamson',
                'orange_cap_runs': 735,
                'orange_cap_team': 'Sunrisers Hyderabad',
                'purple_cap_player': 'Andrew Tye',
                'purple_cap_wickets': 24,
                'purple_cap_team': 'Kings XI Punjab',
                'total_sixes': 872,
                'total_fours': 1920,
                'total_runs': 19900,
                'total_matches': 60,
                'theme_color': '#F59E0B',
                'congratulation_message': '🎉 Congratulations Chennai Super Kings! 2018 Champions under Captain MS Dhoni (Won by 8 wickets)! 🏆'
            },
            {
                'year': 2019,
                'winner_team': 'Mumbai Indians',
                'winner_code': 'MI',
                'runner_up': 'Chennai Super Kings',
                'final_venue': 'Rajiv Gandhi International Stadium, Hyderabad',
                'final_margin': 'Won by 1 run',
                'player_of_season': 'Rohit Sharma',
                'orange_cap_player': 'David Warner',
                'orange_cap_runs': 692,
                'orange_cap_team': 'Sunrisers Hyderabad',
                'purple_cap_player': 'Imran Tahir',
                'purple_cap_wickets': 26,
                'purple_cap_team': 'Chennai Super Kings',
                'total_sixes': 784,
                'total_fours': 1870,
                'total_runs': 19200,
                'total_matches': 60,
                'theme_color': '#004BA0',
                'congratulation_message': '🎉 Congratulations Mumbai Indians! 4th IPL Title under Captain Rohit Sharma in 2019 (Won by 1 run)! 🏆'
            },
            {
                'year': 2020,
                'winner_team': 'Mumbai Indians',
                'winner_code': 'MI',
                'runner_up': 'Delhi Capitals',
                'final_venue': 'Dubai International Stadium, Dubai',
                'final_margin': 'Won by 5 wickets',
                'player_of_season': 'Rohit Sharma',
                'orange_cap_player': 'KL Rahul',
                'orange_cap_runs': 670,
                'orange_cap_team': 'Kings XI Punjab',
                'purple_cap_player': 'Kagiso Rabada',
                'purple_cap_wickets': 30,
                'purple_cap_team': 'Delhi Capitals',
                'total_sixes': 734,
                'total_fours': 1820,
                'total_runs': 18950,
                'total_matches': 60,
                'theme_color': '#004BA0',
                'congratulation_message': '🎉 Congratulations Mumbai Indians! 5th IPL Title under Captain Rohit Sharma in 2020 (Won by 5 wickets)! 🏆'
            },
            {
                'year': 2021,
                'winner_team': 'Chennai Super Kings',
                'winner_code': 'CSK',
                'runner_up': 'Kolkata Knight Riders',
                'final_venue': 'Dubai International Stadium, Dubai',
                'final_margin': 'Won by 27 runs',
                'player_of_season': 'MS Dhoni',
                'orange_cap_player': 'Ruturaj Gaikwad',
                'orange_cap_runs': 635,
                'orange_cap_team': 'Chennai Super Kings',
                'purple_cap_player': 'Harshal Patel',
                'purple_cap_wickets': 32,
                'purple_cap_team': 'Royal Challengers Bangalore',
                'total_sixes': 687,
                'total_fours': 1750,
                'total_runs': 18400,
                'total_matches': 60,
                'theme_color': '#F59E0B',
                'congratulation_message': '🎉 Congratulations Chennai Super Kings! 4th IPL Title under Captain MS Dhoni in 2021 (Won by 27 runs)! 🏆'
            },
            {
                'year': 2022,
                'winner_team': 'Gujarat Titans',
                'winner_code': 'GT',
                'runner_up': 'Rajasthan Royals',
                'final_venue': 'Narendra Modi Stadium, Ahmedabad',
                'final_margin': 'Won by 7 wickets',
                'player_of_season': 'Hardik Pandya',
                'orange_cap_player': 'Jos Buttler',
                'orange_cap_runs': 863,
                'orange_cap_team': 'Rajasthan Royals',
                'purple_cap_player': 'Yuzvendra Chahal',
                'purple_cap_wickets': 27,
                'purple_cap_team': 'Rajasthan Royals',
                'total_sixes': 1062,
                'total_fours': 2017,
                'total_runs': 24100,
                'total_matches': 74,
                'theme_color': '#1E293B',
                'congratulation_message': '🎉 Congratulations Gujarat Titans! Debut Season IPL Champions led by Captain Hardik Pandya in 2022 (Won by 7 wickets)! 🏆'
            },
            {
                'year': 2023,
                'winner_team': 'Chennai Super Kings',
                'winner_code': 'CSK',
                'runner_up': 'Gujarat Titans',
                'final_venue': 'Narendra Modi Stadium, Ahmedabad',
                'final_margin': 'Won by 5 wickets',
                'player_of_season': 'MS Dhoni',
                'orange_cap_player': 'Shubman Gill',
                'orange_cap_runs': 890,
                'orange_cap_team': 'Gujarat Titans',
                'purple_cap_player': 'Mohammed Shami',
                'purple_cap_wickets': 28,
                'purple_cap_team': 'Gujarat Titans',
                'total_sixes': 1124,
                'total_fours': 2174,
                'total_runs': 25300,
                'total_matches': 74,
                'theme_color': '#F59E0B',
                'congratulation_message': '🎉 Congratulations Chennai Super Kings! 5th IPL Trophy under Captain MS Dhoni in 2023 (Won by 5 wickets)! 🏆'
            },
            {
                'year': 2024,
                'winner_team': 'Kolkata Knight Riders',
                'winner_code': 'KKR',
                'runner_up': 'Sunrisers Hyderabad',
                'final_venue': 'MA Chidambaram Stadium, Chennai',
                'final_margin': 'Won by 8 wickets',
                'player_of_season': 'Shreyas Iyer',
                'orange_cap_player': 'Virat Kohli',
                'orange_cap_runs': 741,
                'orange_cap_team': 'Royal Challengers Bengaluru',
                'purple_cap_player': 'Harshal Patel',
                'purple_cap_wickets': 24,
                'purple_cap_team': 'Punjab Kings',
                'total_sixes': 1260,
                'total_fours': 2280,
                'total_runs': 27100,
                'total_matches': 74,
                'theme_color': '#6F2DA8',
                'congratulation_message': '🎉 Congratulations Kolkata Knight Riders! 3rd IPL Championship under Captain Shreyas Iyer in 2024 (Won by 8 wickets)! 🏆'
            },
            {
                'year': 2025,
                'winner_team': 'Royal Challengers Bengaluru',
                'winner_code': 'RCB',
                'runner_up': 'Punjab Kings',
                'final_venue': 'M. Chinnaswamy Stadium, Bengaluru',
                'final_margin': 'Won by 6 runs',
                'player_of_season': 'Rajat Patidar',
                'orange_cap_player': 'B Sai Sudharsan',
                'orange_cap_runs': 759,
                'orange_cap_team': 'Gujarat Titans',
                'purple_cap_player': 'Prasidh Krishna',
                'purple_cap_wickets': 25,
                'purple_cap_team': 'Gujarat Titans',
                'total_sixes': 1290,
                'total_fours': 2310,
                'total_runs': 27800,
                'total_matches': 74,
                'theme_color': '#DC2626',
                'congratulation_message': '🎉 Congratulations Royal Challengers Bengaluru! Maiden IPL Trophy 2025 triumph under Captain Rajat Patidar (Won by 6 runs)! 🏆'
            },
            {
                'year': 2026,
                'winner_team': 'Royal Challengers Bengaluru',
                'winner_code': 'RCB',
                'runner_up': 'Gujarat Titans',
                'final_venue': 'M. Chinnaswamy Stadium, Bengaluru',
                'final_margin': 'Won by 5 wickets',
                'player_of_season': 'Rajat Patidar',
                'orange_cap_player': 'Vaibhav Sooryavanshi',
                'orange_cap_runs': 776,
                'orange_cap_team': 'Rajasthan Royals',
                'purple_cap_player': 'Kagiso Rabada',
                'purple_cap_wickets': 29,
                'purple_cap_team': 'Gujarat Titans',
                'total_sixes': 1310,
                'total_fours': 2350,
                'total_runs': 28200,
                'total_matches': 74,
                'theme_color': '#DC2626',
                'congratulation_message': '🎉 Congratulations Royal Challengers Bengaluru! Back-to-Back 2nd IPL Championship in 2026 under Captain Rajat Patidar (Won by 5 wickets)! 🏆'
            },
        ]

        for sdata in seasons_data:
            season = Season.objects.create(**sdata)
            self.stdout.write(f"Created IPL {season.year} Season object...")

            p_stats = [
                (sdata['orange_cap_player'], sdata['orange_cap_team'], sdata['orange_cap_runs'], int(sdata['orange_cap_runs'] * 0.72), int(sdata['orange_cap_runs']/18), int(sdata['orange_cap_runs']/24), 2, 8.1),
                ('Virat Kohli', 'Royal Challengers Bengaluru', int(sdata['orange_cap_runs']*0.91), int(sdata['orange_cap_runs']*0.68), int(sdata['orange_cap_runs']/22), int(sdata['orange_cap_runs']/21), 0, 7.5),
                ('Rajat Patidar', 'Royal Challengers Bengaluru', int(sdata['orange_cap_runs']*0.85), int(sdata['orange_cap_runs']*0.60), int(sdata['orange_cap_runs']/20), int(sdata['orange_cap_runs']/19), 0, 8.0),
                ('Rohit Sharma', 'Mumbai Indians', int(sdata['orange_cap_runs']*0.84), int(sdata['orange_cap_runs']*0.63), int(sdata['orange_cap_runs']/20), int(sdata['orange_cap_runs']/23), 0, 8.0),
                ('Suryakumar Yadav', 'Mumbai Indians', int(sdata['orange_cap_runs']*0.82), int(sdata['orange_cap_runs']*0.52), int(sdata['orange_cap_runs']/19), int(sdata['orange_cap_runs']/17), 0, 7.9),
                ('Shreyas Iyer', 'Kolkata Knight Riders', int(sdata['orange_cap_runs']*0.80), int(sdata['orange_cap_runs']*0.58), int(sdata['orange_cap_runs']/18), int(sdata['orange_cap_runs']/20), 0, 7.7),
                ('Shubman Gill', 'Gujarat Titans', int(sdata['orange_cap_runs']*0.81), int(sdata['orange_cap_runs']*0.60), int(sdata['orange_cap_runs']/17), int(sdata['orange_cap_runs']/26), 0, 7.6),
                (sdata['purple_cap_player'], sdata['purple_cap_team'], 145, 98, 14, 6, sdata['purple_cap_wickets'], 6.8),
            ]

            for p_name, team, runs, balls, fours, sixes, wkts, econ in p_stats:
                sr = round((runs / balls * 100), 2) if balls > 0 else 135.0
                PlayerSeasonStat.objects.create(
                    season=season,
                    player_name=p_name,
                    team=team,
                    matches=14 + (2 if team in [sdata['winner_team'], sdata['runner_up']] else 0),
                    runs=runs,
                    balls_faced=balls,
                    strike_rate=sr,
                    fours=fours,
                    sixes=sixes,
                    wickets=wkts,
                    economy=econ,
                    highest_score=f"{min(125, int(runs/5.5))}"
                )

            teams = [sdata['winner_team'], sdata['runner_up'], 'Royal Challengers Bengaluru', 'Mumbai Indians', 'Chennai Super Kings', 'Kolkata Knight Riders', 'Delhi Capitals', 'Sunrisers Hyderabad']
            
            for i in range(1, 11):
                t1 = teams[(i-1) % len(teams)]
                t2 = teams[i % len(teams)]
                if t1 == t2:
                    t2 = teams[(i+1) % len(teams)]
                w = t1 if i % 2 == 1 else t2
                
                Match.objects.create(
                    season=season,
                    match_number=i,
                    match_stage="League Match" if i < 9 else f"Playoff Q{i-8}",
                    team1=t1,
                    team2=t2,
                    winner=w,
                    win_margin=f"Won by {12 + i*3} runs" if i%2==1 else f"Won by {3 + (i%5)} wickets",
                    toss_winner=t1,
                    toss_decision="Bat" if i%2==0 else "Field",
                    venue="Wankhede Stadium, Mumbai" if i%2==1 else "Eden Gardens, Kolkata",
                    player_of_match=sdata['player_of_season'],
                    team1_runs=160 + (i * 7) % 65,
                    team1_wickets=4 + (i % 5),
                    team2_runs=155 + (i * 5) % 60,
                    team2_wickets=5 + (i % 4)
                )

            Match.objects.create(
                season=season,
                match_number=11,
                match_stage="FINAL CHAMPIONSHIP MATCH",
                team1=sdata['winner_team'],
                team2=sdata['runner_up'],
                winner=sdata['winner_team'],
                win_margin=sdata['final_margin'],
                toss_winner=sdata['winner_team'],
                toss_decision="Field" if "wickets" in sdata['final_margin'] else "Bat",
                venue=sdata['final_venue'],
                player_of_match=sdata['player_of_season'],
                team1_runs=188,
                team1_wickets=5,
                team2_runs=184,
                team2_wickets=8
            )

        self.stdout.write(self.style.SUCCESS("IPL Database Seeding Updated Successfully with exact Orange & Purple Cap Winners!"))
